[package]
name = "counter"
version = "0.0.1"
authors = ["Kotaro Chikuba <miz404@gmail.com>"]

[dependencies]
stdweb = "0.4.2"
yew = { git = "https://github.com/DenisKolodin/yew.git", branch = "master" }